#!/usr/bin/env bash

set -ex

# Modified from https://github.com/jenkinsci/docker-ssh-slave project.

# Usage:
#  docker run jenkinsci/ssh-slave <public key>
# or
#  docker run -e "JENKINS_AGENT_SSH_PUBLIC_KEY=<public key>" jenkinsci/ssh-slave

write_key() {
    mkdir -p "${JENKINS_AGENT_HOME}/.ssh"
    echo "$1" >"${JENKINS_AGENT_HOME}/.ssh/authorized_keys"
    chown -Rf jenkins:jenkins "${JENKINS_AGENT_HOME}/.ssh"
    chmod 0700 -R "${JENKINS_AGENT_HOME}/.ssh"
}

if [[ "${JENKINS_AGENT_SSH_PUBLIC_KEY}" == ssh-* ]]; then
    echo "\${JENKINS_AGENT_SSH_PUBLIC_KEY}: ${JENKINS_AGENT_SSH_PUBLIC_KEY}"
    write_key "${JENKINS_AGENT_SSH_PUBLIC_KEY}"
fi
if [[ $# -gt 0 ]]; then
    if [[ $1 == ssh-* ]]; then
        write_key "$1"
        shift 1
    else
        exec "$@"
    fi
fi

# ensure variables passed to docker container are also exposed to ssh sessions
env | grep _ >>/etc/environment

ssh-keygen -A
exec /usr/sbin/sshd -D -e "${@}"
